{
  "uid" : "42b180e56ca0ce54",
  "name" : "test_modify_approve",
  "fullName" : "tests.brownie.token.tests.test_approve#test_modify_approve",
  "historyId" : "955e3f6226713de80a392f10c503148c",
  "time" : {
    "start" : 1643744635970,
    "stop" : 1643744635970,
    "duration" : 0
  },
  "status" : "broken",
  "statusMessage" : "ValueError: Transaction simulation failed: Error processing Instruction 0: insufficient funds for instruction",
  "statusTrace" : "brownie_project = <Project 'TokenProject'>\naccounts = <brownie.network.account.Accounts object at 0x7f27c1e1ab50>\n\n    @pytest.fixture(scope=\"module\")\n    def token(brownie_project, accounts):\n>       return brownie_project.Token.deploy(\"Test Token\", \"TST\", 18, 1e21, {'from': accounts[0]})\n\ntests/brownie/token/tests/conftest.py:49: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n../../../.local/share/virtualenvs/neon-compatibility-g882AfFF/lib/python3.8/site-packages/brownie/network/contract.py:600: in __call__\n    return tx[\"from\"].deploy(\n../../../.local/share/virtualenvs/neon-compatibility-g882AfFF/lib/python3.8/site-packages/brownie/network/account.py:508: in deploy\n    receipt, exc = self._make_transaction(\n../../../.local/share/virtualenvs/neon-compatibility-g882AfFF/lib/python3.8/site-packages/brownie/network/account.py:743: in _make_transaction\n    exc = VirtualMachineError(e)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = VirtualMachineError(ValueError({'code': -32002, 'message': 'Transaction simulation failed: Error processing Instructio...0 compute units', 'Program eeLSJgWzzxrqKv1UxtRVVH8FX3qCQWUs9QuAjJpETGU failed: insufficient funds for instruction']}}))\nexc = {'code': -32002, 'data': {'accounts': None, 'err': {'InstructionError': [0, 'InsufficientFunds']}, 'logs': ['Program e...ion']}, 'message': 'Transaction simulation failed: Error processing Instruction 0: insufficient funds for instruction'}\n\n    def __init__(self, exc: ValueError) -> None:\n        try:\n            exc = exc.args[0]\n        except Exception:\n            pass\n    \n        if isinstance(exc, dict) and \"message\" in exc:\n            if \"data\" not in exc:\n                raise ValueError(exc[\"message\"]) from None\n    \n            self.message: str = exc[\"message\"].rstrip(\".\")\n    \n            if isinstance(exc[\"data\"], str):\n                # handle parity exceptions - this logic probably is not perfect\n                if \"0x08c379a0\" in exc[\"data\"]:\n                    revert_type, err_msg = [i.strip() for i in exc[\"data\"].split(\"0x08c379a0\", 1)]\n                    err_msg = eth_abi.decode_abi([\"string\"], HexBytes(err_msg))\n                    err_msg = f\"{revert_type} '{err_msg}'\"\n                elif exc[\"data\"].endswith(\"0x\"):\n                    err_msg = exc[\"data\"][:-2].strip()\n                else:\n                    err_msg = exc[\"data\"]\n                raise ValueError(f\"{self.message}: {err_msg}\") from None\n    \n            try:\n                txid, data = next((k, v) for k, v in exc[\"data\"].items() if k.startswith(\"0x\"))\n            except StopIteration:\n>               raise ValueError(exc[\"message\"]) from None\nE               ValueError: Transaction simulation failed: Error processing Instruction 0: insufficient funds for instruction\n\n../../../.local/share/virtualenvs/neon-compatibility-g882AfFF/lib/python3.8/site-packages/brownie/exceptions.py:104: ValueError",
  "flaky" : false,
  "newFailed" : false,
  "newBroken" : false,
  "newPassed" : false,
  "retriesCount" : 0,
  "retriesStatusChange" : false,
  "beforeStages" : [ {
    "name" : "token",
    "time" : {
      "start" : 1643744630462,
      "stop" : 1643744635535,
      "duration" : 5073
    },
    "status" : "broken",
    "statusMessage" : "ValueError: Transaction simulation failed: Error processing Instruction 0: insufficient funds for instruction\n",
    "statusTrace" : "  File \"/home/runner/.local/share/virtualenvs/neon-compatibility-g882AfFF/lib/python3.8/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/runner/.local/share/virtualenvs/neon-compatibility-g882AfFF/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/home/runner/.local/share/virtualenvs/neon-compatibility-g882AfFF/lib/python3.8/site-packages/_pytest/fixtures.py\", line 932, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/home/runner/work/neon-compatibility/neon-compatibility/tests/brownie/token/tests/conftest.py\", line 49, in token\n    return brownie_project.Token.deploy(\"Test Token\", \"TST\", 18, 1e21, {'from': accounts[0]})\n  File \"/home/runner/.local/share/virtualenvs/neon-compatibility-g882AfFF/lib/python3.8/site-packages/brownie/network/contract.py\", line 600, in __call__\n    return tx[\"from\"].deploy(\n  File \"/home/runner/.local/share/virtualenvs/neon-compatibility-g882AfFF/lib/python3.8/site-packages/brownie/network/account.py\", line 508, in deploy\n    receipt, exc = self._make_transaction(\n  File \"/home/runner/.local/share/virtualenvs/neon-compatibility-g882AfFF/lib/python3.8/site-packages/brownie/network/account.py\", line 743, in _make_transaction\n    exc = VirtualMachineError(e)\n  File \"/home/runner/.local/share/virtualenvs/neon-compatibility-g882AfFF/lib/python3.8/site-packages/brownie/exceptions.py\", line 104, in __init__\n    raise ValueError(exc[\"message\"]) from None\n",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : true,
    "hasContent" : true
  } ],
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "feature",
    "value" : "Brownie"
  }, {
    "name" : "parentSuite",
    "value" : "tests.brownie.token.tests"
  }, {
    "name" : "suite",
    "value" : "test_approve"
  }, {
    "name" : "host",
    "value" : "fv-az124-999"
  }, {
    "name" : "thread",
    "value" : "3722-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.brownie.token.tests.test_approve"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "history" : {
      "statistic" : {
        "failed" : 0,
        "broken" : 10,
        "skipped" : 0,
        "passed" : 0,
        "unknown" : 0,
        "total" : 10
      },
      "items" : [ {
        "uid" : "edfa08e6501c0a0d",
        "reportUrl" : "https://neonlabsorg.github.io/neon-compatibility/devnet-aws/devnet-aws-faucet-fix/605//#testresult/edfa08e6501c0a0d",
        "status" : "broken",
        "statusDetails" : "requests.exceptions.ReadTimeout: HTTPConnectionPool(host='3.13.67.238', port=9090): Read timed out. (read timeout=30)",
        "time" : {
          "start" : 1643742912689,
          "stop" : 1643742912689,
          "duration" : 0
        }
      }, {
        "uid" : "a116668e630a296f",
        "reportUrl" : "https://neonlabsorg.github.io/neon-compatibility/devnet-aws/devnet-aws-faucet-fix/600//#testresult/a116668e630a296f",
        "status" : "broken",
        "statusDetails" : "requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='3.13.67.238', port=9090): Max retries exceeded with url: /solana (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fe7204a4580>, 'Connection to 3.13.67.238 timed out. (connect timeout=30)'))",
        "time" : {
          "start" : 1643716329098,
          "stop" : 1643716329098,
          "duration" : 0
        }
      }, {
        "uid" : "c578709b8f3c1319",
        "reportUrl" : "https://neonlabsorg.github.io/neon-compatibility/devnet-aws/devnet-aws-faucet-fix/597//#testresult/c578709b8f3c1319",
        "status" : "broken",
        "statusDetails" : "requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='3.13.67.238', port=9090): Max retries exceeded with url: /solana (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f4a4ef76a30>, 'Connection to 3.13.67.238 timed out. (connect timeout=30)'))",
        "time" : {
          "start" : 1643706917351,
          "stop" : 1643706917351,
          "duration" : 0
        }
      }, {
        "uid" : "c961f93e22432e17",
        "reportUrl" : "https://neonlabsorg.github.io/neon-compatibility/devnet-aws/devnet-aws-faucet-fix/594//#testresult/c961f93e22432e17",
        "status" : "broken",
        "statusDetails" : "requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='3.13.67.238', port=9090): Max retries exceeded with url: /solana (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f2a67afb6d0>, 'Connection to 3.13.67.238 timed out. (connect timeout=30)'))",
        "time" : {
          "start" : 1643681392564,
          "stop" : 1643681392564,
          "duration" : 0
        }
      }, {
        "uid" : "b211e59302f087ad",
        "reportUrl" : "https://neonlabsorg.github.io/neon-compatibility/devnet-aws/devnet-aws-faucet-fix/588//#testresult/b211e59302f087ad",
        "status" : "broken",
        "statusDetails" : "requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='3.13.67.238', port=9090): Max retries exceeded with url: /solana (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb98da6ca30>, 'Connection to 3.13.67.238 timed out. (connect timeout=30)'))",
        "time" : {
          "start" : 1643617513397,
          "stop" : 1643617513397,
          "duration" : 0
        }
      }, {
        "uid" : "198721193b0686e3",
        "reportUrl" : "https://neonlabsorg.github.io/neon-compatibility/devnet-aws/devnet-aws-faucet-fix/583//#testresult/198721193b0686e3",
        "status" : "broken",
        "statusDetails" : "requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='3.13.67.238', port=9090): Max retries exceeded with url: /solana (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fa7ce084a30>, 'Connection to 3.13.67.238 timed out. (connect timeout=30)'))",
        "time" : {
          "start" : 1643550455812,
          "stop" : 1643550455812,
          "duration" : 0
        }
      }, {
        "uid" : "f26b7d42dc7c5bea",
        "reportUrl" : "https://neonlabsorg.github.io/neon-compatibility/devnet-aws/devnet-aws-faucet-fix/578//#testresult/f26b7d42dc7c5bea",
        "status" : "broken",
        "statusDetails" : "requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='3.13.67.238', port=9090): Max retries exceeded with url: /solana (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fccb90dc400>, 'Connection to 3.13.67.238 timed out. (connect timeout=30)'))",
        "time" : {
          "start" : 1643486382323,
          "stop" : 1643486382323,
          "duration" : 0
        }
      }, {
        "uid" : "eb141f8414f79134",
        "reportUrl" : "https://neonlabsorg.github.io/neon-compatibility/devnet-aws/devnet-aws-faucet-fix/575//#testresult/eb141f8414f79134",
        "status" : "broken",
        "statusDetails" : "requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='3.13.67.238', port=9090): Max retries exceeded with url: /solana (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fd9d70a0b80>, 'Connection to 3.13.67.238 timed out. (connect timeout=30)'))",
        "time" : {
          "start" : 1643478136743,
          "stop" : 1643478136743,
          "duration" : 0
        }
      }, {
        "uid" : "182b3e1be86f0dc",
        "reportUrl" : "https://neonlabsorg.github.io/neon-compatibility/devnet-aws/devnet-aws-faucet-fix/574//#testresult/182b3e1be86f0dc",
        "status" : "broken",
        "statusDetails" : "requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='3.13.67.238', port=9090): Max retries exceeded with url: /solana (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f25a0c7d550>, 'Connection to 3.13.67.238 timed out. (connect timeout=30)'))",
        "time" : {
          "start" : 1643477430783,
          "stop" : 1643477430783,
          "duration" : 0
        }
      } ]
    },
    "tags" : [ ]
  },
  "source" : "42b180e56ca0ce54.json",
  "parameterValues" : [ ]
}